### ISSUE TITLE
Definir tecnologias

### ISSUE THREAD

**Issue by lbrunofidelis** [UnBPaquera/Wiki#11]
**Descrição**
Definir arquitetura da aplicação baseado no tema e escopo do projeto.

**Tasks**
 * [x] Definir Tecnologias

**Critérios de Aceitação**
 * [x] Adicionar Referência
 * [x] Markdown

**Comment by lucasqmc** [comment]
Separei alguns links uteis que utilizei para tirar algumas conclusões sobre tecnologias e arquitetura:

*node.js distance between coordinates: (DISTANCIA ENTRE AS COORDENADAS)
    
  https://www.npmjs.com/package/geolib
  https://www.npmjs.com/package/geo-distance
  https://gist.github.com/mattpowell/3380070
  https://stackoverflow.com/questions/31776914/best-way-to-find-distance-between-two-geopointslats-longs-in-node-js
  https://www.npmjs.com/package/google-distance
  https://www.reddit.com/r/reactnative/comments/7bg55s/how_to_calculate_distance_between_locations_in/
  https://stackoverflow.com/questions/50636284/calculating-distance-in-react-native


*python distance between coordinates: (DISTANCIA ENTRE AS COORDENADAS)

  https://janakiev.com/blog/gps-points-distance-python/
  https://pypi.org/project/geopy/
  https://www.w3resource.com/python-exercises/math/python-math-exercise-27.php

Conclusão: Ambas as tecnologias possuem mecanismos para manusear coordenadas e calcular
distancia entre elas.O node possui maior numero de bibliotecas prontas e tutoriais(video-aulas)
com aplicações semelhantes além de utilizar a mesma linguagem que react-native, o que facilita
o aprendizado.


*get phone location react-native:

    

  https://www.npmjs.com/package/react-native-get-location
  https://alligator.io/react/geolocation-react-native/
  https://reactnative.dev/docs/geolocation

*fluter vs react-native:

  https://www.thedroidsonroids.com/blog/flutter-vs-react-native-what-to-choose-in-2020

  *Pinterest é feito com react-native
  *Tinder e sua adoção do mongodb:
  https://www.quora.com/Why-does-Tinder-use-MongoDB-rather-than-RDBMS  

Comentários sobre o flutter:  

    I have a Flutter app with 1.6 million downloads (Android + iOS) and I can say:
-
1) It is NOT stable (I'm forced to use beta channel because current "stable" channel won't work on any device with Adreno 308 (Samsung J4+, J6+ and J7 Prime)).

2) There is a lot of silly breaking changes (for instance, last version broke an important plugin because of the adition of one method in a interface (considering that Dart doesn't have interfaces, only abstract classes, this is stupid, because it is completely avoidable))

3) It is NOT fast. Dart benchmark are very near JavaScript V8 speed (google it) and the application itself is waaaay slower than native (not near 60FPS, not even in a OnePlus 6 with 8Gb RAM). But the Flutter framework is awesome in this sense (it's very easy to make a billion rows list with no performance issues at all).

4) Dart is a tremendous stupid language. Even simple things as JSON deserialization is a pain (you have to run a code generator to do this in a typed manner, because it lacks reflection capabilities). And the UI declaration is awful (methods(inside(methods(inside(methods,with,lots,of,comas))))))))) <-- the number of ) is right?)

Thanks fro more clear about Flutter Framework.
Flutter is very usefully, i am also working with flutter app development. Flutter is easy framework for Android and iOS app development.

-
The main benefit of Flutter over React Native (and native, in general) is the lack of platform constraints. Flutter isn’t muzzled by the platform UI because it doesn’t use it; it renders everything by itself. This frees you to build the best UX without compromise – and it’s the primary difference between Flutter and React Native. Read more here >>


I'd add:

Flutter doesn't use native UI views, this means that they don't get the system optimizations for views. This becomes very clear when the battery starts rapidly draining.

ex: UIKit knows that when a UIViewController is presented on top of another, it can stop drawing the views in the first ViewController. Flutter will just keep drawing every single element, every frame. I think it will be very difficult for Google to overcome this issue as the execution is different across platforms, and possibly gets into private API territory (which gets your app rejected).

Disclaimer: I work on Expo. However the expo modules are agnostic of React Native and could be used in Flutter.

https://www.reddit.com/r/reactnative/comments/9uf835/can_someone_give_me_good_reasons_why_i_should/e94t1ka/

Estrutura de grafos com mongo e javascript:

  https://www.compose.com/articles/graph-data-with-mongodb/
  https://pt.slideshare.net/interviewcoach/building-a-social-network-with-mongodb-74467821



  Links uteis sobre a estrutura de dados e o banco:

    https://www.vertabelo.com/blog/a-dating-app-data-model/
    http://www.databaseanswers.org/data_models/dating_sites/index.htm
    https://hackernoon.com/how-to-build-a-dating-application-55d5ca0c8f5c
    https://mlsdev.com/blog/120-how-to-build-a-good-dating-app

Comentário sobre o uso do mongodb:
 
Some recommend standalone MongoDB for such apps, which is not the best way. Most such recommendations arise from myths
surrounding MongoDB, checkout the video below to learn about myths surrounding MongoDB.

Tinder itself used MongoDB and ran into many issues. It got to a point where they were
eventually forced to move their focus from product to scaling the service.    

https://www.reddit.com/r/node/comments/6onhqi/react_express_social_network/

**Comment by lbrunofidelis** [comment]
Não foi possível definir a arquitetura pois o tamanho da aplicação ainda está sendo mensurado.
As tecnologias foram definidas e o documento está completo.
